apiVersion: v2
name: default-network-policy
description: Network policies managed by ACM Governance.
type: application
version: 0.1.0
keywords:
  - Policy
  - Security
  - Governance
dependencies:
  - name: commonlib
    version: 0.2.2
    repository: https://finastra-engineering.github.io/fusion-operate-charts
