apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-learning-cluster
  namespace: policies
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: class
        operator: In
        values:
          - learning
