apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: network-policy-helm
  namespace: policies
  annotations:
    policy.open-cluster-management.io/standards: null
    policy.open-cluster-management.io/categories: null
    policy.open-cluster-management.io/controls: null
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: network-policy-helm-prod-ns
        spec:
          remediationAction: inform
          severity: low
          namespaceSelector:
            exclude:
              - kube-*
              - openshift-*
            include:
              - "*"
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: NetworkPolicy
                apiVersion: networking.k8s.io/v1
                metadata:
                  name: allow-same-namespace
                spec:
                  podSelector: {}
                  ingress:
                    - from:
                        - podSelector: {}
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-network-policy-helm
  namespace: policies
placementRef:
  name: placement-network-policy-helm
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: network-policy-helm
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-network-policy-helm
  namespace: policies
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: class
        operator: In
        values:
          - learning
      - key: region
        operator: In
        values:
          - eastus
