apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: config-data-policies
policyDefaults:
  namespace: policies
  placement:
    placementRulePath: input/placementrule.yaml
  remediationAction: inform
  severity: medium
policies:
  - name: policy-app-config-aliens
    disabled: false
    manifests:
      - path: input/configmap-aliens.yaml
    remediationAction: inform
    namespaceSelector:
      exclude:
        - kube-*
        - openshift-*
      include:
        - "*"
