apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  labels:
    app: np-helm
  name: np-helm-app
  namespace: policies
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - np-helm
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: medium
  labels:
    app: np-helm
  name: np-helm-chan
  namespace: policies
spec:
  pathname: https://github.com/vbelouso/acm-policies.git
  type: GitHub
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: np-helm
  name: np-helm-placement
  namespace: policies
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: local-cluster
        operator: In
        values:
          - "true"
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: default-network-policy-helm
  labels:
    app: np-helm
  name: np-helm-sub
  namespace: policies
spec:
  channel: policies/np-helm-chan
  placement:
    placementRef:
      kind: PlacementRule
      name: np-helm-placement
